nginx:
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./build:/usr/share/nginx/html
    # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # - ./cali.config:/etc/nginx/conf.d/default.conf:ro
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - /etc/ssl/certs:/etc/ssl/certs:ro    
build:
  image: node:latest
  working_dir: /data
  command: npm run build
  volumes:
    - ./:/data
renew_certs:
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./build:/usr/share/nginx/html
    - /etc/letsencrypt:/etc/letsencrypt
    - ./renew_certs.sh:/root/renew_certs.sh
  command: /root/renew_certs.sh

# Generate certs from LetsEncrypt
# Inside running nginx, follow steps:
#     - echo "deb http://httpredir.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/sources.list
#     - apt-get update
#     - apt-get install certbot -t jessie-backports
#     - certbot certonly --webroot -w /usr/share/nginx/html -d calinoracation.com -d www.calinoracation.com
