nginx:
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./build:/usr/share/nginx/html
    - /etc/letsencrypt:/etc/letsencrypt
build:
  image: node:latest
  working_dir: /data
  volumes:
    - ./:/data

# Generate certs from LetsEncrypt
# Inside running nginx, follow steps:
#     - echo "deb http://httpredir.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/sources.list
#     - apt-get update
#     - apt-get install certbot -t jessie-backports
#     - certbot certonly --webroot -w /usr/share/nginx/html -d calinoracation.com -d www.calinoracation.com