nginx:
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./build:/usr/share/nginx/html:ro
build:
  image: node:latest
  working_dir: /data
  entrypoint: npm i && npm run build
  volumes:
    - ./:/data